# Generated by Django 3.2.16 on 2023-01-29 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
