# Generated by Django 3.2.16 on 2023-01-29 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
